### ISSUE TITLE
Design a common server response format.

### ISSUE THREAD

**Issue by gvJaime** [malariaspot/MicroSpot-WiFi#17]
It must be easy and fast to parse

**Comment by alexx666** [comment]
We should use JSON as a response. As for its contents here is a sample:

{	
	"status":"success/error",
	"code":"successOrErrorCode",
	"message":"ayy lmao",
	"data": {
		"x": 25,
		"y":7.5
	}
}

"data" is optional and should only be used  when additional information is required, for instance the position or light intensity.
