### ISSUE TITLE
use Serial1 driver for Uno WiFi. access the esp at 230400 baud.

### ISSUE THREAD

**Issue by JAndrassy** [malariaspot/MicroSpot-WiFi#25]
Implements[ Serial1 of Arduino Uno WiFi Developer Edition board](https://github.com/jandrassy/UnoWiFiDevEdSerial1) to access the on-board ESP8266 at 230400 baud.

The library is a driver for SC16IS750 implemented for Arduino Uno WiFi Developer Edition as Serial1. This driver is necessary to communicate with the on-board ESP8266 over it's serial interface. The included tool EspProxy enables accessing the on-board ESP8266 at 115200 baud over USB for 'flashing' tools (esptool, FDM), IDE sketch upload and Serial Monitor.

**Comment by JAndrassy** [comment]
I created the driver, but at the beginning some months ago, it was your Uno WiFi know-how, what helped me to start explore the Uno WiFi possibilities

**Comment by gvJaime** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Responder al issue de Microspot-WiFi](https://trello.com/c/8GOlcEa5/1-responder-al-issue-de-microspot-wifi)

**Comment by gvJaime** [comment]
Hello @jandrassy 

We're glad that our repo helped you make the best from your ESP8266 board. It is always a pleasure to contribute to a new development.

Just by curiosity, how did our repo help you in your project?

Also, is this an issue within our firmware? if not, should I close this issue?

**Comment by JAndrassy** [comment]
Sorry, no issue with your firmware, only a way to communicate. Your [Wiki page about Arduino Uno WiF](https://github.com/malariaspot/MicroSpot-WiFi/wiki/Arduino-UNO-WiFi-ESP8266-Arduino-core-compatibility-notes)i was the help.
And the library I created for the Uno WiFi could help you for fast communication between Atmega and esp8266 on Uno WiFi.
